sudo: required
services:
  - docker

before_install:
  - docker build -t juanmiguelar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true juanmiguelar/docker-react npm run test

notifications:
  email:
    recipients:
      - juanmiguelar09@gmail.com
    on_success: never # default: change
    on_failure: always # default: always